using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone
{
    public class NameList
    {
        public NameList()
        {
            try
            {
                string[] nameFile = File.ReadAllLines("RandomNames.txt");

                for (int i = 0; i < nameFile.Length; i++)
                {
                    char[] c = nameFile[i].ToCharArray();
                    c[0] = char.ToUpper(c[0]);

                    string name = new string(c);

                    name = name.Trim();
                    name = "\"" + name + "\",";

                    File.AppendAllText("NameOutput.txt", name + "\n");
                }
            }
            catch { }
        }

        public static string[] NameArray = new string[]
        {
            "Batman",
            "Aileron",
            "Francis",
            "Monet",
            "Nelle",
            "Magen",
            "Marcos",
            "Lino",
            "Alfonso",
            "Marie",
            "Calvin",
            "Gertrud",
            "Amalia",
            "Evelin",
            "Imelda",
            "Billy",
            "Silvana",
            "Josephine",
            "Melva",
            "Tiara",
            "Dana",
            "Sandie",
            "Dudley",
            "Matilda",
            "Anthony",
            "Angeles",
            "Thi",
            "Tena",
            "Michale",
            "Maryanna",
            "Kiara",
            "Liane",
            "Nicolette",
            "Allyson",
            "Micah",
            "Hien",
            "Jone",
            "Graig",
            "Karry",
            "Vernice",
            "Latonya",
            "Carl",
            "Cara",
            "Clarissa",
            "Arnold",
            "Drusilla",
            "Ingrid",
            "Jeana",
            "Shari",
            "Michal",
            "Randee",
            "Meggan",
            "Virgie",
            "Mireille",
            "Concepcion",
            "Orville",
            "Sheba",
            "Kathaleen",
            "Jan",
            "Hope",
            "Dewey",
            "Sharee",
            "Leoma",
            "Alfredia",
            "Taneka",
            "Caren",
            "Tori",
            "Rodrick",
            "Dominique",
            "Lachelle",
            "Ardell",
            "Natacha",
            "Jessica",
            "Loren",
            "Jackie",
            "Wendolyn",
            "Elia",
            "Leonore",
            "Yasuko",
            "Heather",
            "Kortney",
            "Rob",
            "Jaunita",
            "Jamar",
            "Jone",
            "Kathie",
            "Alyce",
            "Kaleigh",
            "Katy",
            "Carina",
            "Faustina",
            "Caleb",
            "Jene",
            "Eusebia",
            "Otto",
            "Noe",
            "Tana",
            "Kimberlie",
            "Aide",
            "Lorilee",
            "Remona",
            "Johanna",
            "Robyn",
            "Adele",
            "Beckie",
            "Berry",
            "Windy",
            "Terence",
            "Randa",
            "Sherron",
            "Darell",
            "Gerard",
            "Jerry",
            "Suanne",
            "Tana",
            "Breana",
            "Krystal",
            "Hertha",
            "Madalyn",
            "Ling",
            "Goldie",
            "Willy",
            "Jami",
            "Easter",
            "Florencia",
            "Tien",
            "Sherise",
            "Florance",
            "Carmel",
            "Sibyl",
            "Jacklyn",
            "Jackson",
            "Shawn",
            "Randolph",
            "Alan",
            "Laurinda",
            "Mackenzie",
            "Misha",
            "Mozell",
            "Susannah",
            "Kasha",
            "Janene",
            "Regan",
            "Honey",
            "Randy",
            "Harrison",
            "Kristal",
            "Bambi",
            "Shasta",
            "Agustina",
            "Refugia",
            "Minnie",
            "Paulette",
            "Mauro",
            "Lucina",
            "Boris",
            "Jonathon",
            "Haydee",
            "Chantell",
            "Claire",
            "Valorie",
            "Bertie",
            "Caryl",
            "Ling",
            "Stewart",
            "Thu",
            "Wilford",
            "Athena",
            "Cira",
            "Rachael",
            "Jarred",
            "Gertrud",
            "Luvenia",
            "Shemeka",
            "Tierra",
            "Isobel",
            "Laila",
            "Shizuko",
            "Danyel",
            "Emelina",
            "Joannie",
            "Honey",
            "Lavonda",
            "Shawanna",
            "Cristopher",
            "Huey",
            "Erasmo",
            "Nubia",
            "Regan",
            "Vanessa",
            "Leigha",
            "Kena",
            "Devona",
            "Annita",
            "Miquel",
            "Kacy",
            "Claretha",
            "Daron",
            "Horacio",
            "Chrystal",
            "Tyesha",
            "Martina"
        };

    }
}
